# Generated by Django 3.0 on 2021-04-09 13:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='identifier',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=255, null=True, unique=True),
        ),
    ]
